--------------------------------------------------------
--  Fichier créé - jeudi-avril-01-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PERSONNE
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."PERSONNE" 
   (	"IDENTIFIANT" NUMBER(*,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(80 BYTE), 
	"METIER" VARCHAR2(80 BYTE), 
	"NUM_TEL" NUMBER(*,0), 
	"PRIX_HEURE" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SOUMAYA.PERSONNE
SET DEFINE OFF;
Insert into SOUMAYA.PERSONNE (IDENTIFIANT,NOM,PRENOM,ADRESSE,EMAIL,METIER,NUM_TEL,PRIX_HEURE) values (653,'soumaya','yussef','nnbhb','kkbkjkh','jhkjhj',22,22);
Insert into SOUMAYA.PERSONNE (IDENTIFIANT,NOM,PRENOM,ADRESSE,EMAIL,METIER,NUM_TEL,PRIX_HEURE) values (5,'mohamed 123','bensassi','2rue','med@esprit.tn','professeur',5060,22);
Insert into SOUMAYA.PERSONNE (IDENTIFIANT,NOM,PRENOM,ADRESSE,EMAIL,METIER,NUM_TEL,PRIX_HEURE) values (2,'bensassi','soumaya','2rue','sou@aaa','med',2060,22);
Insert into SOUMAYA.PERSONNE (IDENTIFIANT,NOM,PRENOM,ADRESSE,EMAIL,METIER,NUM_TEL,PRIX_HEURE) values (21,'amir','aaa','aa','aa@aaa','aaa',235,235);
Insert into SOUMAYA.PERSONNE (IDENTIFIANT,NOM,PRENOM,ADRESSE,EMAIL,METIER,NUM_TEL,PRIX_HEURE) values (121,'bensassi','soumaya','2rue','soumaya.bensassi@esprit.tn','medecin',555,11);
--------------------------------------------------------
--  DDL for Index PERSONNE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUMAYA"."PERSONNE_PK" ON "SOUMAYA"."PERSONNE" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PERSONNE
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."PERSONNE" ADD CONSTRAINT "PERSONNE_PK" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SOUMAYA"."PERSONNE" MODIFY ("IDENTIFIANT" NOT NULL ENABLE);
